spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/encuestas
    username: encuestas
    password: encuestas
  jpa:
    hibernate:
      ddl-auto: validate       # Validamos esquema (las tablas las creará Flyway)
    open-in-view: false
  data:
    mongodb:
      uri: mongodb://encuestas:encuestas@localhost:27017/encuestas?authSource=admin

  flyway:
    enabled: true
    locations: classpath:db/migration

# Configuración de Swagger UI (springdoc)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Configuración JWT (EJEMPLO — cambia el secreto en producción)
jwt:
  secret: "Enc0ntr4rUnS3cr3t0!"
  accessTokenMinutes: 15
  issuer: "encuestas-app"

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
